packages:
  - 'apps/*'
  - 'packages/*'
autoInstallPeers: true
allowBuilds:
  '@parcel/watcher': true
  less: true
  nx: true
  sharp: true
  unrs-resolver: true
  '@nestjs/core': true
  '@swc/core': true
  '@prisma/engines': true
  'prisma': true
  'msgpackr-extract': true
