import { db } from '@hiveforge/database';
import { ai } from '@hiveforge/ai-runtime';

export interface PlannedTask {
  id: string;
  title: string;
  description: string;
  workerType: 'Research' | 'Finance' | 'Marketing' | 'Operations' | string;
  input: any;
  dependencies: string[];
}

export class MissionPlanner {
  async planMission(missionId: string): Promise<PlannedTask[]> {
    // 1. Fetch Mission details
    const mission = await db.mission.findUnique({
      where: { id: missionId },
    });

    if (!mission) {
      throw new Error(`Mission with ID "${missionId}" not found.`);
    }

    // 2. Update status to PLANNING
    await db.mission.update({
      where: { id: missionId },
      data: { status: 'PLANNING' },
    });

    await db.activity.create({
      data: {
        missionId,
        type: 'MISSION_PLANNING_STARTED',
        message: 'AI Planner is decomposing the mission into a structured task graph.',
      },
    });

    // 3. Construct prompt for the AI Planner
    const systemPrompt = `You are the HiveForge Mission Planner. Your task is to decompose a high-level goal into a structured Directed Acyclic Graph (DAG) of tasks. 
Each task must be assigned to exactly one of the following specialized AI worker roles:
- "Research" (for competitor analysis, market studies, product gaps)
- "Finance" (for budgeting, worksheets, pricing models)
- "Marketing" (for social media copy, launch slogans, ads)
- "Operations" (for supplier outreach, delivery setup, logistic planning)

You MUST return a JSON object with a single property "tasks" containing an array of task objects.
Each task object MUST have:
- "id": A unique string ID (e.g. "task-1", "task-2")
- "title": A concise, action-oriented title
- "description": A detailed explanation of what this task must achieve
- "workerType": The exact worker role string ("Research", "Finance", "Marketing", "Operations")
- "input": A JSON object containing the context/input parameters for the worker
- "dependencies": An array of task IDs that this task depends on (must be completed before this task starts)

Ensure the dependencies form a valid DAG (no cycles, no self-dependencies).`;

    const userPrompt = `Decompose the following mission goal:
Mission Title: ${mission.title}
Mission Description: ${mission.description}
Priority: ${mission.priority}

Generate a clear 3-5 task workflow that successfully achieves this goal step-by-step.`;

    try {
      const response = await ai.generateCompletion({
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt },
        ],
        jsonMode: true,
      });

      const parsed = JSON.parse(response.content) as { tasks: PlannedTask[] };
      const plannedTasks = parsed.tasks || [];

      if (plannedTasks.length === 0) {
        throw new Error('AI Planner returned an empty task graph.');
      }

      // 4. Save tasks in database using a transaction
      await db.$transaction(async (tx) => {
        // Map temporary IDs generated by LLM (like "task-1") to actual database UUIDs
        const idMapping = new Map<string, string>();

        for (const planned of plannedTasks) {
          const taskRecord = await tx.task.create({
            data: {
              missionId,
              title: planned.title,
              description: planned.description,
              workerType: planned.workerType,
              input: planned.input || {},
              status: 'PENDING',
            },
          });
          idMapping.set(planned.id, taskRecord.id);
        }

        // Save dependencies using the mapping
        for (const planned of plannedTasks) {
          const taskId = idMapping.get(planned.id)!;
          for (const depId of planned.dependencies) {
            const dependsOnTaskId = idMapping.get(depId);
            if (dependsOnTaskId) {
              await tx.taskDependency.create({
                data: {
                  taskId,
                  dependsOnTaskId,
                },
              });
            }
          }
        }

        // Update tasks that have dependencies to WAITING_DEPENDENCIES state
        const allCreatedTasks = await tx.task.findMany({
          where: { missionId },
          include: { dependencies: true },
        });

        for (const t of allCreatedTasks) {
          if (t.dependencies.length > 0) {
            await tx.task.update({
              where: { id: t.id },
              data: { status: 'WAITING_DEPENDENCIES' },
            });
          }
        }

        // Create MissionVersion snapshot
        await tx.missionVersion.create({
          data: {
            missionId,
            version: 1,
            snapshot: plannedTasks as any,
          },
        });

        // 5. Update Mission status to QUEUED (ready for execution)
        await tx.mission.update({
          where: { id: missionId },
          data: { status: 'QUEUED' },
        });

        await tx.activity.create({
          data: {
            missionId,
            type: 'MISSION_PLANNED',
            message: `Successfully generated execution graph with ${plannedTasks.length} tasks. Status updated to QUEUED.`,
          },
        });
      });

      return plannedTasks;
    } catch (error: any) {
      // Rollback to FAILED status on error
      await db.mission.update({
        where: { id: missionId },
        data: { status: 'FAILED' },
      });

      await db.activity.create({
        data: {
          missionId,
          type: 'MISSION_PLANNING_FAILED',
          message: `Planning failed: ${error.message}`,
        },
      });

      throw error;
    }
  }
}

export const planner = new MissionPlanner();
