import { db } from '@hiveforge/database';
import { planner } from '@hiveforge/planner';
import { scheduler } from '@hiveforge/scheduler';

async function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function runDemo() {
  console.log('🏁 Starting HiveForge E2E Execution Test...\n');

  // 1. Ensure Demo Workspace Context is seeded
  console.log('👤 Seeding database workspace context...');
  let org = await db.organization.findFirst({ where: { name: 'Demo Org' } });
  if (!org) {
    org = await db.organization.create({ data: { name: 'Demo Org' } });
  }

  let user = await db.user.findUnique({ where: { email: 'demo@hiveforge.com' } });
  if (!user) {
    user = await db.user.create({
      data: {
        email: 'demo@hiveforge.com',
        name: 'Senthil',
        passwordHash: 'demo-password-hash',
        organizationId: org.id
      }
    });
  }

  let workspace = await db.workspace.findFirst({
    where: { organizationId: org.id, name: 'Acme Retail' }
  });
  if (!workspace) {
    workspace = await db.workspace.create({
      data: {
        organizationId: org.id,
        name: 'Acme Retail',
        industry: 'Retail',
        description: 'Stationery & Kids Store'
      }
    });

    await db.userRole.create({
      data: {
        userId: user.id,
        workspaceId: workspace.id,
        role: 'ADMIN'
      }
    });
  }
  console.log(`✅ Loaded Workspace: "${workspace.name}" (ID: ${workspace.id})`);

  // 2. Start the Task Queue Scheduler
  console.log('🤖 Starting the Scheduler...');
  await scheduler.startScheduler();

  // 3. Create a Demo Mission
  const title = 'Stationery Store Local Launch Campaign';
  const description = 'Deconstruct a plan to set up a new local stationery and craft store in Acme Retail Area with $500 total budget.';
  console.log(`📝 Creating Draft Mission: "${title}"`);
  
  const mission = await db.mission.create({
    data: {
      workspaceId: workspace.id,
      title,
      description,
      priority: 'HIGH',
      status: 'DRAFT'
    }
  });

  await db.activity.create({
    data: {
      missionId: mission.id,
      type: 'MISSION_CREATED',
      message: `Mission "${title}" created as a draft.`
    }
  });

  // 4. Decompose the goal using the AI Planner
  console.log('🧠 AI Planner: Decomposing goal into dependency task graph...');
  const plannedTasks = await planner.planMission(mission.id);
  console.log(`✅ Decomposed into ${plannedTasks.length} tasks:`);
  plannedTasks.forEach((t, i) => {
    console.log(`   ${i + 1}. [${t.workerType}] ${t.title} (Depends on: [${t.dependencies.join(', ')}])`);
  });

  // 5. Trigger Mission Execution
  console.log('\n🚀 Triggering Mission Execution Pipeline...');
  await scheduler.triggerMissionExecution(mission.id);

  // 6. Poll status until complete
  console.log('⏳ Polling database status for task completion logs...');
  let attempts = 0;
  const maxAttempts = 60; // 60 seconds max timeout
  let finalStatus = 'RUNNING';

  while (attempts < maxAttempts) {
    await sleep(1000);
    attempts++;

    const currentMission = await db.mission.findUnique({
      where: { id: mission.id },
      include: {
        tasks: {
          select: { title: true, status: true, workerType: true }
        }
      }
    });

    if (!currentMission) {
      console.error('❌ Mission deleted unexpectedly.');
      break;
    }

    const statuses = currentMission.tasks.map(t => `${t.title} (${t.workerType}): ${t.status}`).join('\n      ');
    console.log(`   [Second ${attempts}] Mission Status: ${currentMission.status}`);
    console.log(`      ${statuses}\n`);

    if (currentMission.status === 'COMPLETED' || currentMission.status === 'FAILED') {
      finalStatus = currentMission.status;
      break;
    }
  }

  // 7. Print deliverables on success
  if (finalStatus === 'COMPLETED') {
    console.log('🎉 MISSION SUCCEEDED! Reading generated deliverables:\n');

    const deliverables = await db.artifact.findMany({
      where: {
        task: {
          missionId: mission.id
        }
      },
      include: {
        versions: {
          orderBy: { version: 'desc' },
          take: 1
        },
        task: true
      }
    });

    deliverables.forEach(d => {
      console.log(`======================================================================`);
      console.log(`📦 DELIVERABLE: ${d.title} (${d.type})`);
      console.log(`Generated by Task: ${d.task.title} (${d.task.workerType})`);
      console.log(`======================================================================`);
      console.log(d.versions[0]?.content || '(No content generated)');
      console.log(`\n`);
    });
  } else {
    console.error('❌ Mission execution failed or timed out.');
  }

  // 8. Clean up and exit
  console.log('🛑 Stopping scheduler and closing connections...');
  await scheduler.stopScheduler();
  await db.$disconnect();
  console.log('👋 Demo completed.');
}

runDemo().catch(err => {
  console.error('❌ Demo script crashed:', err);
  process.exit(1);
});
